# Generated by Django 5.0.3 on 2026-04-23 13:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_orderevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Код')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percent', max_length=16, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, help_text='Для процента — число 1..100. Для фиксированной — сумма в RUB.', max_digits=10, verbose_name='Значение скидки')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Мин. сумма заказа')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 — без ограничений', verbose_name='Лимит активаций')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='Активаций')),
                ('once_per_user', models.BooleanField(default=True, verbose_name='Один раз на пользователя')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Сумма скидки')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Использован')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promo.coupon', verbose_name='Промокод')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='orders.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['coupon', 'user'], name='promo_coupo_coupon__d3736d_idx')],
            },
        ),
    ]
