# Generated by Django 5.0.3 on 2026-04-23 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_support_ticket_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.PositiveIntegerField(db_index=True, verbose_name='ID UserDigitalAccess')),
                ('product_id', models.PositiveIntegerField(db_index=True, verbose_name='ID товара')),
                ('digital_item_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID DigitalItem')),
                ('token_jti', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='JTI подписанной ссылки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('success', models.BooleanField(default=True, verbose_name='Успех')),
                ('reason', models.CharField(blank=True, max_length=128, verbose_name='Причина отказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Событие скачивания',
                'verbose_name_plural': 'Журнал скачиваний',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='securityevent',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Успешный вход'), ('login_failed', 'Неуспешный вход'), ('logout', 'Выход'), ('register', 'Регистрация'), ('password_change', 'Смена пароля'), ('password_reset_request', 'Запрос сброса пароля'), ('password_reset_done', 'Сброс пароля выполнен'), ('email_verified', 'Email подтверждён'), ('twofa_enabled', '2FA включена'), ('twofa_disabled', '2FA отключена'), ('twofa_failed', 'Неуспешный код 2FA'), ('account_locked', 'Аккаунт заблокирован'), ('account_unlocked', 'Аккаунт разблокирован'), ('order_paid', 'Оплата заказа'), ('order_cancelled', 'Отмена заказа'), ('payment_callback_ok', 'Платёжный callback (ok)'), ('payment_callback_fail', 'Платёжный callback (ошибка/подпись)'), ('digital_download', 'Скачивание/просмотр цифрового товара'), ('admin_action', 'Действие администратора'), ('suspicious_activity', 'Подозрительная активность')], db_index=True, max_length=64, verbose_name='Тип события'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'created_at'], name='core_securi_event_t_e93b36_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', 'created_at'], name='core_securi_user_id_5eb64f_idx'),
        ),
        migrations.AddField(
            model_name='downloadaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_audits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='downloadaudit',
            index=models.Index(fields=['user', 'created_at'], name='core_downlo_user_id_cbe2e0_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadaudit',
            index=models.Index(fields=['product_id', 'created_at'], name='core_downlo_product_ec5175_idx'),
        ),
    ]
