# Generated by Django 5.0.3 on 2026-02-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_25e057_idx',
            old_name='orders_orde_status_0b1862_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('pending_payment', 'Ожидание оплаты'), ('paid', 'Оплачен'), ('failed', 'Неуспешен'), ('cancelled', 'Отменён')], db_index=True, default='created', max_length=32, verbose_name='Статус'),
        ),
    ]
