# Generated by Django 5.0.3 on 2026-04-23 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_deleted_at_order_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Создан'), ('pending_payment', 'Ожидание оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменён'), ('fulfilled', 'Товары выданы'), ('refund', 'Возврат'), ('note', 'Комментарий')], db_index=True, max_length=32, verbose_name='Тип события')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Событие заказа',
                'verbose_name_plural': 'События заказов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='orders_orde_order_i_974e12_idx')],
            },
        ),
    ]
