# Generated by Django 5.0.3 on 2026-02-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='digitalitem',
            new_name='catalog_dig_status_f54eaa_idx',
            old_name='catalog_dig_status_8a0b0d_idx',
        ),
        migrations.AlterField(
            model_name='digitalitem',
            name='item_type',
            field=models.CharField(choices=[('file', 'Файл'), ('key', 'Ключ'), ('link', 'Ссылка'), ('access_code', 'Код доступа')], max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='digitalitem',
            name='max_activations',
            field=models.PositiveIntegerField(default=1, help_text='0 — без ограничений', verbose_name='Количество активаций'),
        ),
        migrations.AlterField(
            model_name='digitalitem',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('reserved', 'Зарезервирован'), ('sold', 'Продан')], db_index=True, default='available', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='license_type',
            field=models.CharField(choices=[('perpetual', 'Бессрочная'), ('subscription', 'Подписка')], db_index=True, max_length=32, verbose_name='Тип лицензии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('game', 'Игра'), ('software', 'ПО'), ('course', 'Курс'), ('media', 'Медиа'), ('asset', 'Asset')], db_index=True, max_length=32, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purpose',
            field=models.CharField(choices=[('personal', 'Личное'), ('business', 'Бизнес')], db_index=True, max_length=16, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('hidden', 'Скрыт'), ('disabled', 'Отключен')], db_index=True, default='active', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=16, verbose_name='Тип'),
        ),
    ]
