# Generated by Django 5.0.3 on 2026-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_design_and_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалён (soft)'),
        ),
        migrations.AlterField(
            model_name='digitalitem',
            name='value',
            field=models.TextField(verbose_name='Значение (зашифровано)'),
        ),
    ]
