# Generated by Django 5.0.3 on 2026-04-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Коды восстановления (хэши)'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Неуспешных попыток входа'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP последнего входа'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ua',
            field=models.CharField(blank=True, max_length=512, verbose_name='User-Agent последнего входа'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован до'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA включена'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, verbose_name='TOTP-секрет'),
        ),
        migrations.AddField(
            model_name='user',
            name='unlock_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='Токен разблокировки'),
        ),
    ]
