# Generated by Django 5.0.3 on 2026-04-23 13:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_orderevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Баланс')),
                ('currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdraw', 'Списание'), ('refund', 'Возврат'), ('bonus', 'Бонус'), ('referral', 'Реферальное вознаграждение')], db_index=True, max_length=16, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Положительное — приход, отрицательное — списание', max_digits=12, verbose_name='Сумма')),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Остаток после операции')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order', verbose_name='Заказ')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='Кошелёк')),
            ],
            options={
                'verbose_name': 'Операция кошелька',
                'verbose_name_plural': 'Операции кошелька',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='wallet_wall_wallet__ccf672_idx')],
            },
        ),
    ]
